### PR TITLE
Fix /order example

### LINKED ISSUE #35: Examples wrong in application
Reference to image:

screen shot 2018-10-09 at 10 47 22 am

It should be /order add in the example!

### PR DESCRIPTION
**Pull request by monmanuela**
Fixes #35

### CODE REVIEW

File: src/main/java/seedu/address/logic/commands/order/AddCommand.java [hunk 1]
```diff
@@ -25,7 +25,7 @@
             + PREFIX_PHONE + "PHONE "
             + PREFIX_ADDRESS + "ADDRESS "
             + PREFIX_FOOD + "FOOD...\n"
-            + "Example: " + COMMAND_WORD + " "
+            + "Example: " + OrderCommand.COMMAND_WORD + " " + COMMAND_WORD + " "
```
Comment (jinyingtan) [inline src/main/java/seedu/address/logic/commands/order/AddCommand.java]: Do add the Date in the example, which was merged in recently

Comment (jinyingtan) [reply src/main/java/seedu/address/logic/commands/order/AddCommand.java]: Update the javadocs for this class `person` -> `order`, `address book` -> `order book`
